//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvProje1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intern
    {
        public byte Id { get; set; }
        public string Department { get; set; }
        public string Company { get; set; }
        public string Years { get; set; }
    }
}
